Header section
fatmahussein/portfolio pull request #2
Opened 2022-12-01 09:00 UTC by fatmahussein

2022-12-01 09:04 UTC, fatmahussein commented
## portfolio:setup and mobile first

Add:
 -index.html
 -styles.css
 -linters

2022-12-01 10:13 UTC, mckent05 requested changes
Hi @fatmahussein,

# STATUS: CHANGES REQUIRED ♻️ ♻️  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/205026050-d1234422-540f-4ae2-8dca-623108d47d7c.gif)

## Highlights
- You have used the right workflow for this project 👍 
- All linter checks are passing ✔️ ✔️ 


## Required Changes ♻️
- I have made suggestions on this PR on the assumption that you have chosen template 3 as your portfolio design, please ensure that your portfolio looks closely like your chosen design template, Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 10:13 UTC, mckent05 commented on index.html
> +    </div>
- According to the project requirement, this section of the page should be wrapped in a `section` tag, semantic tags help to improve the structure of your page. Check [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info 👍. Do not forget to align the content of this section with a `flex` display property in CSS
- Also, as seen in the Figma design, this section contains some background images, please use the `background-image` property in CSS to properly place the background image for this section. You can save the background images from the Figma template by clicking on the section of the page and clicking on the `export` button on the right hand side of the site. 👍 


Your design:
<img width="149" alt="tykr5kt" src="https://user-images.githubusercontent.com/73607512/205023870-cd738866-286f-432f-a355-215aac928a8d.PNG">

Figma Design:
<img width="138" alt="wvve" src="https://user-images.githubusercontent.com/73607512/205024027-4f808b3a-3e0d-4d50-975d-3ff32662128e.PNG">

2022-12-01 10:13 UTC, mckent05 commented on index.html
> +                <div class="header h2">I’m a software developer</div>
- In HTML, it is normally advisable to use `hx` tags when you intend to write headers, it helps to improve the SEO of your website, I suggest using an `h1` tag for this text `Hey there. I’m Fatuma` and a `p` tag for this text `I’m a software developer`. Please fix this 🙏 🙏

2022-12-01 10:13 UTC, mckent05 commented on index.html
> +                    don’t hesitate to contact me.</div>
- As I said earlier please use a `p` tag for this text, it would help improve the semantics of your website, please fix this 🙏 🙏

2022-12-01 10:13 UTC, mckent05 commented on index.html
> +        </div>
- In HTML, when dealing with a list of items, it is advisable to use a `ul` tag, this would help to improve the semantics of your website, please wrap this section in a `ul` tag instead of a `div` tag and wrap individual `img` tag in an `li` tag. Please fix this 😄 😄 
- I suggest using a `flex` display property to align the content of this section because it would help greatly with the responsiveness of your site 👍 👍

2022-12-03 06:35 UTC, fatmahussein commented
## Portfolio:setup and mobile first

add:
 -index.html
-styles.css
-linters

2022-12-03 07:39 UTC, fatmahussein commented
## Portfolio : setup and mobile first

Add:
-index.html
-styles.css
-linters

2022-12-03 07:42 UTC, fatmahussein commented
## Portfolio : Setup and mobile first

Add:
 -index.html
-styles.css
-linters

2022-12-03 09:00 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @fatmahussein , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 10:33 UTC, fatmahussein commented
## Portfolio: setup and mobile first

Add:
-index.html
-styles.css
-linters

2022-12-03 13:26 UTC, Yerimah requested changes
# STATUS: REQUESTED CHANGES 🔴 

Hi @fatmahussein 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![So Close Snl GIF by Saturday Night Live](https://user-images.githubusercontent.com/71140133/205443063-1bf7d347-6626-403d-baa5-e411f11fa130.gif)


 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ descriptive Pull Request
✅ Good Commit messages

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 13:26 UTC, Yerimah commented on index.html
> +            </div>
- [ ] Kindly reduce the space on the top of your toolbar to make your design as close to the Figma design as possible. 

> Your Design
![Oops](https://user-images.githubusercontent.com/71140133/205442278-5170504b-3e4a-46d8-b004-4736faf1de7f.PNG)

> Figma Design Template
![headal](https://user-images.githubusercontent.com/71140133/205442295-36746f0c-8cf7-47c8-a281-a4788f1a6972.PNG)

2022-12-03 13:26 UTC, Yerimah commented on styles.css
> +  width: 20px;
- [ ] I would kindly suggest you remove the `position: absolute;` property on the social media icons to reposition them because `position:` absolute; takes the element out of the document flow. it is very important you stick with the Figma design template as much as possible.

> Your Design
![socialsunal](https://user-images.githubusercontent.com/71140133/205442922-6e8ba5c6-f6a6-4697-89fc-35e15edf7d94.PNG)

> Figma Design Template
![headal](https://user-images.githubusercontent.com/71140133/205442934-26efca50-b5ea-4402-87fa-2631d8715c03.PNG)

2022-12-06 10:04 UTC, fatmahussein commented
## Portfolio: Setup and mobile first

Add: 
-index.html
-styles.css
-linter

2022-12-06 12:02 UTC, frank1738 approved these changes
Hi @fatmahussein , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/WOBKl5b0epgbBkdPPL/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay

## Optional suggestions



- [ ] I noted that you provided your PR Description as a comment and did not write it in the correct place.

![image](https://user-images.githubusercontent.com/98453979/205905769-23a0f11d-c9cc-4e09-8ddb-93382aac7fdf.png)

- [ ] Kindly note that you can edit the pull request description by clicking on the three-dotted button as shown below

![image](https://user-images.githubusercontent.com/98453979/205906181-92f6e2b2-81d4-47a6-b705-d4578cac3305.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 12:46 UTC, merged