update middle section
fatmahussein/portfolio pull request #4
Opened 2022-12-09 12:22 UTC by fatmahussein

## Portfolio : finish mobile version

Add:
 - Works section
 - About myself section

2022-12-09 12:31 UTC, ha-manel reviewed
# STATUS: INVALID 🔴 
Hi @fatmahussein 
I'm sure you put a lot of effort into this project but this PR is invalid because you have unedited README file😓 please use this [template](https://github.com/microverseinc/readme-template)

Kindly fix the issue and submit the PR for review again 👍 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 17:49 UTC, huseyinbiyik commented
Hi @fatmahussein,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

- You have submitted a project, that has no license file. Kindly add a license file, MIT is recommended, and submit for review again.👍
- There is a conflict on this branch please fix that as well.🙃

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-09 19:56 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @fatmahussein, :wave: 

Good Work So Far!!! :+1:  
You are almost done. There are some issues you need to fix before you move to the next project.

## Highlights 🌟

![Alt Text](https://media.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy.gif)
✔️ Linters checks are passing
✔️ Use GitHub Flow
✔️ Meaningful commit messages.

## Required Changes ♻️

- [ ] Kindly `rename` the file `LICENCE.md` as `MIT.md`, so that it can be consistent with `MIT` link of Readme file.
  ![Screenshot from 2022-12-10 01-26-43](https://user-images.githubusercontent.com/60083437/206782131-7ed02c60-d3e0-4624-aadb-27c04155e147.png)

- [ ] I can see many comments in the `CSS` file. Kindly remove the comments to make your code clean and readable.


_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 19:56 UTC, Tufahel commented on index.html
> +        <div class="grid-item">4</div>-->
- [ ] Kindly remove the `comments` from the code-base so that your code looks clean and readable.

2022-12-09 19:56 UTC, Tufahel commented on styles.css
> +}
- [ ] When I increased the size of the screen a bit from `400px to 728px`, the design inside the `about me` section collapsed. `Frameworks` and `Skills` override the other designs. The design should be consistent with all the mobile screen sizes. Kindly fix this.
  ![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/60083437/206778803-baaea2ee-ef83-43c1-9aac-4f509171f2e9.gif)

2022-12-09 19:56 UTC, Tufahel commented on index.html
> +            <h4 id="lang">Languages</h4>
- [ ] As per the [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122), there should be a `down arrow` on the right side of `Languages`. Kindly fix this to match the design.
  - ***Your Design***
    ![Screenshot from 2022-12-10 01-11-02](https://user-images.githubusercontent.com/60083437/206779770-1418cf34-9ce7-459f-a28b-2df87f274451.png)

  - ***Figma Design***
  ![Screenshot from 2022-12-10 01-13-54](https://user-images.githubusercontent.com/60083437/206779972-2a1589ef-3b3d-420b-a541-67573a0406d4.png)

2022-12-09 19:56 UTC, Tufahel commented on styles.css
> +}
- [ ] Cards/Grids should be in the `middle` for all `mobile screens`. But, when I increase the size of the screen a bit from `400px to 728px` the cards move to the `left side` of the screen. Kindly fix this.

  ![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/60083437/206781310-aeafb9b3-572f-4979-bf47-59e8532ccd2d.gif)

2022-12-09 19:56 UTC, Tufahel commented on styles.css
> +
- [ ] The space from `text to tags` and `tags to button (See Project)` should be the same as per the [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122). Kindly fix this to match the design.
  - ***Your Design***
  ![Screenshot from 2022-12-10 01-40-53](https://user-images.githubusercontent.com/60083437/206784293-2b9c58c2-0998-4a09-97b4-1673aedbb88b.png)

  - ***Figma Design**
  ![Screenshot from 2022-12-10 01-45-40](https://user-images.githubusercontent.com/60083437/206784658-89520b3f-f211-4320-a6aa-a73071a16373.png)

2022-12-09 19:56 UTC, Tufahel commented on index.html
> +               </div>
- [ ] Great Work :+1:  on implementing `click` interactions on `button` for `See Project` and `Get my Resume`. Kindly implement other button interactions for those `buttons` to match the project requirements.
  - ***Requirement***
  ![Screenshot from 2022-12-10 00-08-39](https://user-images.githubusercontent.com/60083437/206765709-1e19c086-0e12-42d4-8f02-d36392abc793.png)

  - You can consider adding following styles:

```
/* Enabled */
color: #6070FF;
background: #FFFFFF;

/* Hover */
color: #FFFFFF;
background: #6070FF;

/* Pressed */
color: #FFFFFF;
background: #2230D2;

/* Disabled */
color: #5E6C84;
background: #FFFFFF;
```

![Screenshot from 2022-12-10 00-07-00](https://user-images.githubusercontent.com/60083437/206765582-f046bdd5-94c0-4989-8127-d2d086b4e963.png)

2022-12-10 15:07 UTC, jerryowusu requested changes
Hi @fatmahussein 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![almost-there-reach](https://user-images.githubusercontent.com/65233860/206861406-93571455-561c-4980-adb0-fa5e5d165a7e.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Neat and well organised code :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 15:07 UTC, jerryowusu commented on styles.css
> +}
As requested by the previous reviewer, the cards should be in the middle of the screen, but it shifts to the left side when you stretch and increase the width of the screen. Kindly check and ensure that it has even margins on both left and right and does not shift to the side. :pray: 

![Screenshot from 2022-12-10 15-02-17](https://user-images.githubusercontent.com/65233860/206861635-c5381099-a828-4700-be5a-f529ba456314.png)

2022-12-10 15:07 UTC, jerryowusu commented on README.md
> +=======
[OPTIONAL] Your readme file is missing key headers/sections like the `Key Features`  and `Future Features`. Kindly ensure that all sections of the microverse readme template and present. :wink:

2022-12-10 17:31 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @fatmahussein, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

_**Kindly check an optional comment I left under the review and please work on it**_ :pray: 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/933d15a5d5acd62a4c99c1e2b391cacfbfe61154e349c4af39c9a99d8d10caab/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f3236444f6f4477644e474b416736554b492f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 17:31 UTC, Qoosim commented on README.md
> +=======
[OPTIONAL] Your readme file is missing key headers/sections like the Key Features and Future Features. Kindly ensure that all sections of the microverse readme template and present. wink

2022-12-10 17:38 UTC, merged